### PR TITLE
BLoC logic implemented

### PR DESCRIPTION
**Pull request by juanpablo-pereira**
### Classes added:
- #### Bloc: States what any Bloc must have
- #### IDiceBloc: Adds streams and the roll functionality as a requirement for any DiceBloc
- #### DiceBloc: Implements all the requirements for rolling and publishing new dice values and the score

dice-bloc-gif

### CODE REVIEW

**Review by FranciscoGaraventa — CHANGES_REQUESTED** [review]
Remember that the name of files are in lower case separate every word with '_'

**Review by FranciscoGaraventa — APPROVED** [review]
LGTM!

**Review by MarcosCGlobant — CHANGES_REQUESTED** [review]
If dice_bloc_rollable is he interface for the DiceBloc, you should rename the file and the abstract class to IDiceBloc and i_dice_bloc to keep consistency with the convention

**Review by MarcosCGlobant — APPROVED** [review]
LGTM

**Pull request merged**
